/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _MainLayoutRouteImport } from './routes/__MainLayout'
import { Route as _MainLayoutIndexRouteImport } from './routes/__MainLayout/index'
import { Route as _MainLayoutSettingsRouteImport } from './routes/__MainLayout/settings'
import { Route as _MainLayoutServiceRouteImport } from './routes/__MainLayout/service'
import { Route as _MainLayoutSalesRouteImport } from './routes/__MainLayout/sales'
import { Route as _MainLayoutReportsRouteImport } from './routes/__MainLayout/reports'
import { Route as _MainLayoutInventoryRouteImport } from './routes/__MainLayout/inventory'
import { Route as _MainLayoutFinanceRouteImport } from './routes/__MainLayout/finance'
import { Route as _MainLayoutDashboardRouteImport } from './routes/__MainLayout/dashboard'
import { Route as _MainLayoutCustomersRouteImport } from './routes/__MainLayout/customers'

const _MainLayoutRoute = _MainLayoutRouteImport.update({
  id: '/__MainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _MainLayoutIndexRoute = _MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutSettingsRoute = _MainLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutServiceRoute = _MainLayoutServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutSalesRoute = _MainLayoutSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutReportsRoute = _MainLayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutInventoryRoute = _MainLayoutInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutFinanceRoute = _MainLayoutFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutDashboardRoute = _MainLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _MainLayoutRoute,
} as any)
const _MainLayoutCustomersRoute = _MainLayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => _MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/customers': typeof _MainLayoutCustomersRoute
  '/dashboard': typeof _MainLayoutDashboardRoute
  '/finance': typeof _MainLayoutFinanceRoute
  '/inventory': typeof _MainLayoutInventoryRoute
  '/reports': typeof _MainLayoutReportsRoute
  '/sales': typeof _MainLayoutSalesRoute
  '/service': typeof _MainLayoutServiceRoute
  '/settings': typeof _MainLayoutSettingsRoute
  '/': typeof _MainLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/customers': typeof _MainLayoutCustomersRoute
  '/dashboard': typeof _MainLayoutDashboardRoute
  '/finance': typeof _MainLayoutFinanceRoute
  '/inventory': typeof _MainLayoutInventoryRoute
  '/reports': typeof _MainLayoutReportsRoute
  '/sales': typeof _MainLayoutSalesRoute
  '/service': typeof _MainLayoutServiceRoute
  '/settings': typeof _MainLayoutSettingsRoute
  '/': typeof _MainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__MainLayout': typeof _MainLayoutRouteWithChildren
  '/__MainLayout/customers': typeof _MainLayoutCustomersRoute
  '/__MainLayout/dashboard': typeof _MainLayoutDashboardRoute
  '/__MainLayout/finance': typeof _MainLayoutFinanceRoute
  '/__MainLayout/inventory': typeof _MainLayoutInventoryRoute
  '/__MainLayout/reports': typeof _MainLayoutReportsRoute
  '/__MainLayout/sales': typeof _MainLayoutSalesRoute
  '/__MainLayout/service': typeof _MainLayoutServiceRoute
  '/__MainLayout/settings': typeof _MainLayoutSettingsRoute
  '/__MainLayout/': typeof _MainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/reports'
    | '/sales'
    | '/service'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/reports'
    | '/sales'
    | '/service'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/__MainLayout'
    | '/__MainLayout/customers'
    | '/__MainLayout/dashboard'
    | '/__MainLayout/finance'
    | '/__MainLayout/inventory'
    | '/__MainLayout/reports'
    | '/__MainLayout/sales'
    | '/__MainLayout/service'
    | '/__MainLayout/settings'
    | '/__MainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _MainLayoutRoute: typeof _MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__MainLayout': {
      id: '/__MainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__MainLayout/': {
      id: '/__MainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _MainLayoutIndexRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/settings': {
      id: '/__MainLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _MainLayoutSettingsRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/service': {
      id: '/__MainLayout/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof _MainLayoutServiceRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/sales': {
      id: '/__MainLayout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof _MainLayoutSalesRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/reports': {
      id: '/__MainLayout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof _MainLayoutReportsRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/inventory': {
      id: '/__MainLayout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof _MainLayoutInventoryRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/finance': {
      id: '/__MainLayout/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof _MainLayoutFinanceRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/dashboard': {
      id: '/__MainLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _MainLayoutDashboardRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
    '/__MainLayout/customers': {
      id: '/__MainLayout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof _MainLayoutCustomersRouteImport
      parentRoute: typeof _MainLayoutRoute
    }
  }
}

interface _MainLayoutRouteChildren {
  _MainLayoutCustomersRoute: typeof _MainLayoutCustomersRoute
  _MainLayoutDashboardRoute: typeof _MainLayoutDashboardRoute
  _MainLayoutFinanceRoute: typeof _MainLayoutFinanceRoute
  _MainLayoutInventoryRoute: typeof _MainLayoutInventoryRoute
  _MainLayoutReportsRoute: typeof _MainLayoutReportsRoute
  _MainLayoutSalesRoute: typeof _MainLayoutSalesRoute
  _MainLayoutServiceRoute: typeof _MainLayoutServiceRoute
  _MainLayoutSettingsRoute: typeof _MainLayoutSettingsRoute
  _MainLayoutIndexRoute: typeof _MainLayoutIndexRoute
}

const _MainLayoutRouteChildren: _MainLayoutRouteChildren = {
  _MainLayoutCustomersRoute: _MainLayoutCustomersRoute,
  _MainLayoutDashboardRoute: _MainLayoutDashboardRoute,
  _MainLayoutFinanceRoute: _MainLayoutFinanceRoute,
  _MainLayoutInventoryRoute: _MainLayoutInventoryRoute,
  _MainLayoutReportsRoute: _MainLayoutReportsRoute,
  _MainLayoutSalesRoute: _MainLayoutSalesRoute,
  _MainLayoutServiceRoute: _MainLayoutServiceRoute,
  _MainLayoutSettingsRoute: _MainLayoutSettingsRoute,
  _MainLayoutIndexRoute: _MainLayoutIndexRoute,
}

const _MainLayoutRouteWithChildren = _MainLayoutRoute._addFileChildren(
  _MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _MainLayoutRoute: _MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
